// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanificadorEntrenamientoAPI.Data;

#nullable disable

namespace PlanificadorEntrenamientoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907214746_ConfiguracionRelaciones")]
    partial class ConfiguracionRelaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.DiaRutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDia")
                        .HasColumnType("text");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("DiasRutina");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DiaRutinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("text");

                    b.Property<string>("UrlVideo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiaRutinaId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer");

                    b.Property<float>("Kg")
                        .HasColumnType("real");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("integer");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Rir")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.DiaRutina", b =>
                {
                    b.HasOne("PlanificadorEntrenamientoAPI.Models.Rutina", "Rutina")
                        .WithMany("DiasRutina")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Ejercicio", b =>
                {
                    b.HasOne("PlanificadorEntrenamientoAPI.Models.DiaRutina", "DiaRutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaRutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaRutina");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Rutina", b =>
                {
                    b.HasOne("PlanificadorEntrenamientoAPI.Models.Usuario", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanificadorEntrenamientoAPI.Models.Usuario", "Entrenador")
                        .WithMany()
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Serie", b =>
                {
                    b.HasOne("PlanificadorEntrenamientoAPI.Models.Ejercicio", "Ejercicio")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Usuario", b =>
                {
                    b.HasOne("PlanificadorEntrenamientoAPI.Models.Usuario", "Entrenador")
                        .WithMany("Alumnos")
                        .HasForeignKey("EntrenadorId");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.DiaRutina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Ejercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Rutina", b =>
                {
                    b.Navigation("DiasRutina");
                });

            modelBuilder.Entity("PlanificadorEntrenamientoAPI.Models.Usuario", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
